const info = {
  namespaced: true,
  state() {
    return {
      infos: {
        outer: false,
        number: "HLBU 9468471",
        owner: "HAPAG-LLOYD 赫伯罗特",
        status: "运输中",
        type: "22RT",
        description: "peefer container",
        size: `20' X 8' X 8'6''`,
        tare: "3000",
        payload: "29000",
        news: "The vessel departed from QINGDAO on 2021-01-20.",
        action: [
          {
            name: "入堆",
            place: "1号堆场",
            date: "2021-01-14",
            time: "07:51",
            person: "运输员01",
          },
          {
            name: "转移",
            place: "2号堆场",
            date: "2021-01-14",
            time: "11:58",
            person: "运输员01",
          },
          {
            name: "出堆",
            place: "2号堆场",
            date: "2021-01-20",
            time: "08:23",
            person: "运输员05",
          },
        ],
      },
      manyInfos: [
        {
          outer: false,
          number: "SUDU 1155480",
          owner: "MAERSK 马士基",
          status: "堆场内",
          type: "22RT",
          description: "peefer container",
          size: `20' X 8' X 8'6''`,
          tare: "3200",
          payload: "27280",
          news: "The vessel departed from QINGDAO on 2021-01-20.",
          action: [
            {
              name: "出堆",
              place: "2号堆场",
              date: "2021-02-18",
              time: "23:30",
              person: "运输员02",
              remark: "",
            },
            {
              name: "入堆",
              place: "4号堆场",
              date: "2019-06-02",
              time: "13:24",
              person: "运输员02",
              remark: "",
            },
          ],
        },
        {
          outer: false,
          number: "PONU 2932473",
          owner: "MAERSK 马士基",
          status: "堆场内",
          type: "22RT",
          description: "peefer container",
          size: `20' X 8' X 8'6''`,
          tare: "3200",
          payload: "27280",
          news: "The vessel departed from QINGDAO on 2021-01-20.",
          action: [
            {
              name: "出堆",
              place: "3号堆场",
              date: "2021-02-02",
              time: "23:30",
              person: "运输员02",
              remark: "",
            },
            {
              name: "修理",
              place: "3号堆场",
              date: "2021-12-18",
              time: "13:24",
              person: "维修员02",
              remark: "",
            },
            {
              name: "报修",
              place: "3号堆场",
              date: "2020-12-10",
              time: "15:03",
              person: "安全员02",
              remark: "",
            },
            {
              name: "转移",
              place: "4号堆场",
              date: "2020-12-05",
              time: "10:14",
              person: "运输员02",
              remark: "",
            },
            {
              name: "入堆",
              place: "4号堆场",
              date: "2020-12-01",
              time: "03:27",
              person: "运输员05",
              remark: "",
            },
          ],
        },
        {
          outer: true,
          number: "FCIU 4521291",
          owner: "MSC 地中海",
          status: "运输中",
          type: "22RT",
          description: "peefer container",
          size: `20' X 8' X 8'6''`,
          tare: "2180",
          payload: "28300",
          news: "The vessel departed from QINGDAO on 2021-01-20.",
          action: [
            {
              name: "Loaded",
              place: "HAMBURG",
              date: "2021-02-07",
              time: "07:55",
              way: "ORION",
              voyage: "XPESE0605",
            },
            {
              name: "Vessel departed",
              place: "HAMBURG",
              date: "2021-02-07",
              time: "09:06",
              way: "ORION",
              voyage: "XPESE0605",
            },
            {
              name: "Vessel arrived",
              place: "HAMBURG",
              date: "2021-02-07",
              time: "07:10",
              way: "ORION",
              voyage: "XPESE0605",
            },
            {
              name: "Discharged",
              place: "SOEDERTAELJE",
              date: "2021-02-10",
              time: "11:24",
              way: "ORION",
              voyage: "XPESE0605",
            },
            {
              name: "Departure from",
              place: "SOEDERTAELJE",
              date: "2021-02-10",
              time: "07:21",
              way: "Truck",
              voyage: "",
            },
            {
              name: "Gate in empty",
              place: "SOEDERTAELJE",
              date: "2021-02-11",
              time: "07:21",
              way: "Truck",
              voyage: "",
            },
          ],
        },
        {
          outer: true,
          number: "TCLU 8075745",
          owner: "MAERSK 马士基",
          status: "运输中",
          type: "45GP",
          description: "peefer container",
          size: `40' X 8' X 9'6''`,
          tare: "3890",
          payload: "286100",
          news: "The vessel departed from QINGDAO on 2021-01-20.",
          action: [
            {
              name: "Gate out empty",
              place: "MERSIN",
              date: "2021-02-10",
              time: "15:43",
              way: "Truck",
              voyage: "",
            },
            {
              name: "Arrival in",
              place: "MERSIN",
              date: "2021-02-12",
              time: "01:16",
              way: "Truck",
              voyage: "",
            },
            {
              name: "Loaded",
              place: "MERSIN",
              date: "2021-02-22",
              time: "05:25",
              way: "ZIM CONSTANZA",
              voyage: "75W",
            },
            {
              name: "Vessel departed",
              place: "MERSIN",
              date: "2021-02-22",
              time: "11:18",
              way: "ZIM CONSTANZA",
              voyage: "75W",
            },
            {
              name: "Vessel arrival",
              place: "SAVANNAH,GA",
              date: "2021-03-24",
              time: "03:00",
              way: "ZIM CONSTANZA",
              voyage: "75W",
            },
          ],
        },
      ],
    };
  },
  mutations: {
    setMsg(state: any, infos: object) {
      state.infos = infos;
    },
  },
};

export default info;
